### PR TITLE
👾 transpile-web: add tests

### LINKED ISSUE #12: Time to write goddamn tests

### PR DESCRIPTION
**Pull request by deepsweet**
Closes #12

### CODE REVIEW

**Comment by xaviervia** [comment]
Ohh, I see. That’s perfect.

**Comment by deepsweet** [comment]
Ready.

**Comment by deepsweet** [comment]
```js
const withContent = (
  {
    // TODO: 🤔 default values?
    align: { horizontally, vertically } = {},
    direction,
    reverse,
    shouldWrap
  } = {}
) => pipe(
```

WDYT? I'm not sure that we need to force something here. Maybe just `direction`. Could try a demo of this branch and take a look?

**Comment by deepsweet** [comment]
The main difference now is that "Blocks with different text configurations" are not 100% width, and imo that's the right behaviour :thinking:

**Pull request merged**
