### PR TITLE
➕ transpile-web: shadow support

### PR DESCRIPTION
**Pull request by xaviervia**

### CODE REVIEW

**Comment by deepsweet** [comment]
Told you it's more complicated :cry: 

https://developer.mozilla.org/en-US/docs/Web/CSS/box-shadow

```css
/* offset-x | offset-y | color */
box-shadow: 60px -16px teal;

/* offset-x | offset-y | blur-radius | color */
box-shadow: 10px 5px 5px black;

/* offset-x | offset-y | blur-radius | spread-radius | color */
box-shadow: 2px 2px 2px 1px rgba(0, 0, 0, 0.2);

/* inset | offset-x | offset-y | color */
box-shadow: inset 5em 1em gold;

/* Any number of shadows, separated by commas */
box-shadow: 3px 3px red, -1em 0 0.4em olive;
```

And the didn't provide a specific styles, only one awful shorthand with hundred options.

Thinking about something like this, but haven't tried yet:

```js
const withShadow = ({ offset: { x, y } = {}, inset, color, blur, spread } = {}) => compose(
  style('box-shadow', inset === true, () => 'inset '),
  style('box-shadow', isDef(x) && isDef(y), (prev) => `${prev}${x}px ${x}px `),
  style('box-shadow', isDef(blur), (prev) => `${prev}${blur}px `),
  style('box-shadow', isDef(spread), (prev) => `${prev}${spread}px `),
  style('box-shadow', isDef(color), (prev) => `${prev}${color}`)
)
```

`x`, `y` and `color` should be marked as `isRequired` in prop-types, so I'm not sure if we need `isDef` for them :thinking: On the other hand it should work correctly without a validation package, so let's stick with `isDef` just in case.

**Comment by deepsweet** [comment]
Also:

https://stackoverflow.com/questions/38084120/box-shadowinset-for-react-native

> Increase the borderWidth

I didn't get how it's related.

https://github.com/facebook/react-native/blob/1e8f3b11027fe0a7514b4fc97d0798d3c64bc895/Libraries/Components/View/ShadowPropTypesIOS.js

> shadowRadius: ReactPropTypes.number
> Sets the drop shadow blur radius

So... is it the same as shadow blur for web?

**Comment by deepsweet** [comment]
https://github.com/necolas/react-native-web/blob/5e98107617470eda5b51816c914be02e45982ae8/src/apis/StyleSheet/createReactDOMStyle.js#L75

>// TODO: add inset and spread support

:smile:

**Comment by xaviervia** [comment]
Yep. Good point. I had no idea :D 

I will add support for the `blur-radius` vs `spread-radius` (probably called `blur` and `spread` respectively. I think we can use only one `style` and default anything that is not defined to `0`, since that is the browser default.

About multiple shadows, that can be important for text shadows, but for boxes I suggest we do the same that we did for transforms: support only one. To create multiple shadow requires simply adding another box with the extra shadow.

**Comment by xaviervia** [comment]
I updated the PR with support for `blur` and `spread` as separate properties. Still supporting only one shadow per element, since I think that's the way to go.

> So... is it the same as shadow blur for web?

It seems so. I guess which one is the shadow spread.

**Comment by xaviervia** [comment]
All conflicts solved now, ready to merge if you’re ok with it.

**Comment by deepsweet** [comment]
```js
const withShadow = ({ inset, offset: { x, y } = {}, blur = 0, spread = 0, color } = {}) => (
  style('box-shadow', isDef(x) && isDef(y) && isDef(color), () => `${inset === true ? 'inset ' : ''}${x}px ${y}px ${blur}px ${spread}px ${color}`)
)
```

Thera are only `x`, `y` and `color` are required. WDYT?

**Comment by deepsweet** [comment]
```js
import none from 'ramda/src/none'

export const isDefAll = (...args) => none(isNil)(args)
```

:boom:

**Comment by xaviervia** [comment]
Done & done :)

**Pull request merged**
