### PR TITLE
📦 Packages

### LINKED ISSUE #10: Packages
## List

```
create
create-web
create-native
prefix-client
prefix-server
transpile-web
transpile-native
validate
```

## `create`

```js
import { createLayoutStyles, createTextStyles } from '@lada/create'
import { createLayoutStyles, createTextStyles } from '@lada/create-web'
import { createLayoutStyles, createTextStyles } from '@lada/create-native'
```

Where `create` is a meta-package with different entry points in `package.json`:

```js
"main": "index.web.js",
"react-native": "index.native.js"
```

AFAIK this `react-native` should do the trick.

So if you are not using RN then you just don't need to install it, use `create-web`. Same for RN only. Using both RN and web – install a universal `create`. Packages composition.

Our main "external" packages.

## `prefix-client` / `prefix-server`

```js
import prefixStyles from '@lada/prefix-client'
import prefixStyles from '@lada/prefix-server'
```

Internal packages (in most cases).

## `transpile-web` / `transpile-native`

```js
import { transpileLayoutStyles, transpileTextStyles } from '@lada/transpile-web'
import { transpileLayoutStyles, transpileTextStyles } from '@lada/transpile-native'
```

Internal packages (in most cases).

## `validate`

```js
import { validateLayoutStyles, validateTextStyles } from '@lada/validate'
```

Internal package (in most cases). Should be the same for RN and web.

### PR DESCRIPTION
**Pull request by deepsweet**
Closes #10 – let's create "native" packages with a separate PR.

```
yarn
yarn start demo create-web
```

### CODE REVIEW

**Comment by deepsweet** [comment]
```js
import pipe from 'ramda/src/pipe'
import { transpileLayoutStyles, transpileTextStyles } from '@lada/transpile-web'
import { validateLayoutStyles, validateTextStyles } from '@lada/validate'
import prefixStyles from '@lada/prefix'

export const createLayoutStyles = pipe(
  validateLayoutStyles,
  transpileLayoutStyles,
  prefixStyles
)

export const createTextStyles = pipe(
  validateTextStyles,
  transpileTextStyles,
  prefixStyles
)
```

:heart:

**Comment by deepsweet** [comment]
```
packages
├── create-web
├── prefix
├── transpile-web
└── validate
```

**Comment by deepsweet** [comment]
it's a perfect time to rename it :) what are your options?

**Comment by xaviervia** [comment]
I don’t have a much better suggestion that's the thing. My thinking was to pick a shorter name... but that would easily create confusion. Explicit names are better.

I guess I am not sure about the `create` because is not so much creating them, more like "building" them or just "making" them, but neither of those is much of an improvement.

So it’s OK with create.

**Comment by deepsweet** [comment]
Actually we just totally forgot that it needs to be an alternative to `StyleSheet.create()`, with a nested object passed in. This way, when our `create` package is not only a composition but some iteration and processing as well, it makes a bit more sense :)

**Comment by deepsweet** [comment]
```js
import pipe from 'ramda/src/pipe'
import mapObjIndexed from 'ramda/src/mapObjIndexed'

const createLayoutStyles = mapObjIndexed(
  pipe(
    validateLayoutStyles,
    transpileLayoutStyles,
    prefixStyles
  )
)
```

Ramda :heart:

**Comment by deepsweet** [comment]
I added one example to our current Demo, but it requires a lot of meaningless work to refactor it all. Let's do it right from the beginning in the next version of Demo.

**Pull request merged**
