### PR TITLE
📲 React Native setup and demo

### PR DESCRIPTION
**Pull request by deepsweet**
```
cd packages/create-native/demo/
yarn
yarn ios
yarn android
```

but Android setup is way more complicated than iOS, will provide a detailed guide.

### CODE REVIEW

**Comment by xaviervia** [comment]
Neat

**Comment by deepsweet** [comment]
I can't find a way to require a module outside of demo location... it turned out that RN is using its own packager... with no exposed options like `projectRoots` or something.

[some tech details](https://gist.github.com/alexesDev/071f8935c82ca87a5b46).

**Comment by xaviervia** [comment]
Yes, there are a couple of options on how to bundle RN apps, but it is always a different toolchain, not webpack. It's unfortunate.

**Comment by deepsweet** [comment]
current status after 2 days of a battle: I can make it work with any external file required, but then dependencies of that file can't be found probably because of workspace feature in Yarn...

1. implement your own bundler and modules resolving mechanism
2. ...
3. profit

**Comment by deepsweet** [comment]
I just won :tada: 

next steps:

* create something like this:

```
demo/
  index.js
  index.ios.js
  index.android.js
packages/
  ...
```

i.e. single top-level demo

* rework Start preset and finalize our setup
* Travis

**Comment by deepsweet** [comment]
```
cd demo/
yarn
yarn web
yarn ios
yarn android
```

:man_facepalming:  Android setup still needs a special readme
:man_facepalming: `demo/` is just a separate project with its own dependencies and living completely outside of monorepo and Yarn "workspace" feature – it's just impossible to fight with RN bundler and "external" modules
:man_facepalming: we can't even rename `rn-cli.config.js` despite the fact that we specified it explicitly with `--config`

**Comment by deepsweet** [comment]
I think it's ready to code review, try and merge, I'll finish an overall project setup in a separate PR.

**Pull request merged**
